# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=200)),
                ('session_key', models.CharField(max_length=200)),
                ('token', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
