# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(db_index=True)),
                ('pic_url', models.CharField(max_length=200)),
            ],
        ),
    ]
